### ISSUE TITLE
Confirm Supply has giving error  "Internal JSON-RPC error"

### ISSUE THREAD

**Issue by marquis-ogre** [nhancv/pancake-swap-testnet#5]
Everything worked pefect till 3 days back , but after the feat: fix cake price facing a new issue with the CONFIRM SUPPLY while providing liquidity

![image](https://user-images.githubusercontent.com/39271918/133314453-6b1eb807-3fe1-4f2b-b74d-6a137e168f7f.png)

**Comment by marquis-ogre** [comment]
Solved

**Comment by ditistijn** [comment]
What did you do to fix this? Got the same problem here
